"""add data alerts

Revision ID: 1c6139c660c5
Revises: 1ce8219470f3
Create Date: 2021-02-19 09:33:35.384578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c6139c660c5'
down_revision = '1ce8219470f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_alert_notifications',
        sa.Column('notification_id', sa.String(length=64), nullable=False),
        sa.Column('data_alert_id', sa.String(length=64), nullable=False),
        sa.Column('event', sa.String(length=256), nullable=False),
        sa.Column('project_id', sa.String(length=256), nullable=False),
        sa.Column('title', sa.String(length=256), nullable=False),
        sa.Column('message', sa.String(length=1024), nullable=False),
        sa.Column('data_return_query', sa.String(), nullable=False),
        sa.Column('query_result', sa.JSON(), nullable=False),
        sa.Column('users', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_alert_notifications')
    # ### end Alembic commands ###
